services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: bridge
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - medialocationpathname:/media
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
