services:
  koreader:
    image: wardwouts/koreader-novnc
    container_name: koreader
    ports:
      - "8082:8080"
    environment:
      - CURSOR=
      - EMULATE_READER_H="1080"
      - EMULATE_READER_W="1920"
    volumes:
      - bookslocationpathname:/books
      - ./config:/config
      - ./passwd:/passwd
      - fonts:/usr/lib/koreader/fonts/myfonts
    restart: unless-stopped

volumes:
  passwd:
  fonts: